"""Compute reference equity values used by web/src/engines/__tests__/equity.test.ts.

Run from project root with the venv active:
    source .venv/bin/activate
    python scripts/compute_test_equities.py

Prints values that are hardcoded into the TypeScript tests. Whenever Python's
equity logic (src/utils/equity.py) changes, re-run this and update the test
expectations.
"""
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils.cards import Card
from src.utils.equity import mc_win_prob, river_win_prob

# (hole_str, board_str) cases.
RIVER_CASES = [
    # AsKs on a Broadway board - hero has the nut straight
    (("As", "Ks"), ("Qh", "Jd", "Tc", "5h", "2c")),
    # 7c2d on a dry K-high board - hero has nothing
    (("7c", "2d"), ("Kh", "9d", "4c", "5h", "3s")),
    # Trip aces on a dry board
    (("Ah", "Ad"), ("Ac", "9d", "4c", "5h", "2s")),
]

FLOP_CASES = [
    # AsKs preflop suited connectors on rainbow flop
    (("As", "Ks"), ("Qh", "Jd", "2c")),
    # Pocket aces on dry flop
    (("Ah", "Ad"), ("7c", "5d", "2s")),
    # Suited connectors with flush+straight draw
    (("9h", "8h"), ("7h", "6d", "2c")),
]

TURN_CASES = [
    # Pocket queens on Q-high board
    (("Qh", "Qd"), ("Qs", "8c", "3d", "2h")),
    # AsKs with flush draw + overcards
    (("As", "Ks"), ("Qs", "7s", "2d", "5h")),
]


def hole_ids(pair):
    return tuple(Card(s).id for s in pair)


def board_ids(board):
    return tuple(Card(s).id for s in board)


def main():
    print("// AUTO-REFERENCE values for web/src/engines/__tests__/equity.test.ts")
    print("// Generated by scripts/compute_test_equities.py (Python equity functions are the source of truth).")
    print()

    print("--- River (exact) ---")
    for hole, board in RIVER_CASES:
        eq = river_win_prob(hole_ids(hole), board_ids(board))
        print(f"hole={hole} board={board}  river_win_prob = {eq:.6f}")

    print()
    print("--- Flop (k=5000) ---")
    random.seed(0)
    for hole, board in FLOP_CASES:
        random.seed(0)
        eq = mc_win_prob(hole_ids(hole), board_ids(board), k=5000)
        print(f"hole={hole} board={board}  mc_win_prob(k=5000) = {eq:.6f}")

    print()
    print("--- Turn (k=5000) ---")
    for hole, board in TURN_CASES:
        random.seed(0)
        eq = mc_win_prob(hole_ids(hole), board_ids(board), k=5000)
        print(f"hole={hole} board={board}  mc_win_prob(k=5000) = {eq:.6f}")


if __name__ == "__main__":
    main()
